# Global settings applied to the whole site.  
[build]
  publish = "build"

# Production context: All deploys from the main
# repository branch will inherit these settings.
[context.production]
  command = "yarn build"
  [context.production.environment]
    SERVICE_USERS_PORT=80
    SERVICE_USERS_URL="https://berro-users.netlify.com"
    YARN_VERSION = "1.17.3"
