# Global settings applied to the whole site.  
[build]
  publish = "build"

# Production context: All deploys from the main
# repository branch will inherit these settings.
[context.production]
  command = "yarn build"

  [context.production.environment]
    SERVICE_CASES_URL = "https://berro-cases.netlify.com"
    SERVICE_TASKS_URL = "https://berro-tasks.netlify.com"
    SERVICE_USERS_URL = "https://berro-users.netlify.com"
    YARN_VERSION = "1.17.3"

# A redirect rule with all the supported properties
[[redirects]]
  from = "/*"
  to = "/index.html"

  # The default HTTP status code is 301, but you can define a different one.
  status = 200

  # By default, redirects won't be applied if there's a file with the same 
  # path as the one defined in the `from` property. Setting `force` to `true` 
  # will make the redirect rule take precedence over any existing files.
  force = true
