# Global settings applied to the whole site.  
[build]
  publish = "build"

[build.environment]
  SERVICE_CASES_URL = "https://berro-cases.netlify.com"
  SERVICE_TASKS_URL = "https://berro-tasks.netlify.com"
  SERVICE_USERS_URL = "https://berro-users.netlify.com"
  YARN_VERSION = "1.17.3"
